import { MiniApp } from '@/types';

export const MINI_APPS: MiniApp[] = [
    {
        id: 'todo-list',
        name: 'Todo List',
        description: 'Organize tasks with categories, priorities, and due dates',
        icon: 'list-checks',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'TodoListApp',
    },
    {
        id: 'expense-tracker',
        name: 'Expense Tracker',
        description: 'Track income and expenses with visual breakdown',
        icon: 'wallet',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'ExpenseTrackerApp',
    },
    {
        id: 'random-color',
        name: 'Random Color',
        description: 'Generate random colors in HEX, RGB, or HSL',
        icon: 'palette',
        gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'RandomColorApp',
    },
    {
        id: 'dice-roller',
        name: 'Dice Roller',
        description: 'Roll multiple dice with customizable sides',
        icon: 'dices',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'DiceRollerApp',
    },
    {
        id: 'reaction-time',
        name: 'Reaction Time',
        description: 'Test your reaction speed with statistics',
        icon: 'activity',
        gradient: 'linear-gradient(135deg, #10b981, #06b6d4)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'ReactionTimeApp',
    },
    {
        id: 'square-root',
        name: 'Square Root',
        description: 'Calculate square roots instantly',
        icon: 'square-root',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'SquareRootApp',
    },
    {
        id: 'factorial',
        name: 'Factorial',
        description: 'Calculate factorials (supports large numbers)',
        icon: 'hash',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'FactorialApp',
    },
    {
        id: 'binary-calc',
        name: 'Binary Calculator',
        description: 'Convert between binary and decimal',
        icon: 'binary',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'BinaryCalculatorApp',
    },
    {
        id: 'hex-calc',
        name: 'Hex Calculator',
        description: 'Convert between hexadecimal and decimal',
        icon: 'hash',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'HexCalculatorApp',
    },
    {
        id: 'area-calc',
        name: 'Area Calculator',
        description: 'Calculate area of shapes (square, circle, triangle)',
        icon: 'ruler',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'AreaCalculatorApp',
    },
    {
        id: 'statistics',
        name: 'Statistics',
        description: 'Calculate mean, median, std dev, and more',
        icon: 'trending-up',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'StatisticsApp',
    },
    {
        id: 'fraction',
        name: 'Fraction Calculator',
        description: 'Add, subtract, multiply, divide fractions',
        icon: 'divide',
        gradient: 'linear-gradient(135deg, #f59e0b, #eab308)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'FractionApp',
    },
    {
        id: 'fake-data',
        name: 'Fake Data Generator',
        description: 'Generate fake user data for testing',
        icon: 'users',
        gradient: 'linear-gradient(135deg, #06b6d4, #0ea5e9)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'FakeDataApp',
    },
    {
        id: 'temperature-converter',
        name: 'Temperature Converter',
        description: 'Convert Celsius, Fahrenheit, and Kelvin',
        icon: 'thermometer',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TemperatureApp',
    },
    {
        id: 'power-calc',
        name: 'Power Calculator',
        description: 'Calculate powers and exponents',
        icon: 'zap',
        gradient: 'linear-gradient(135deg, #10b981, #22c55e)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'PowerCalculatorApp',
    },
    {
        id: 'roman-numeral',
        name: 'Roman Numeral',
        description: 'Convert between numbers and Roman numerals',
        icon: 'type',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'RomanNumeralApp',
    },
    {
        id: 'speed-converter',
        name: 'Speed Converter',
        description: 'Convert km/h, mph, and m/s',
        icon: 'gauge',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'SpeedConverterApp',
    },
    {
        id: 'palindrome',
        name: 'Palindrome Checker',
        description: 'Check if text is a palindrome',
        icon: 'check-circle',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'PalindromeApp',
    },
    {
        id: 'prime-number',
        name: 'Prime Number',
        description: 'Check if a number is prime',
        icon: 'hash',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'PrimeNumberApp',
    },
    {
        id: 'leap-year',
        name: 'Leap Year',
        description: 'Check if a year is a leap year',
        icon: 'calendar',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'LeapYearApp',
    },
    {
        id: 'number-guessing',
        name: 'Number Guessing',
        description: 'Guess the number game with hints',
        icon: 'target',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'NumberGuessingApp',
    },
    {
        id: 'word-scramble',
        name: 'Word Scramble',
        description: 'Unscramble words to win',
        icon: 'shuffle',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'WordScrambleApp',
    },
    {
        id: 'character-counter',
        name: 'Character Counter',
        description: 'Count characters, words, and reading time',
        icon: 'type',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'CharacterCounterApp',
    },
    {
        id: 'data-size',
        name: 'Data Size Converter',
        description: 'Convert bytes, KB, MB, GB, TB',
        icon: 'hard-drive',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'DataSizeApp',
    },
    {
        id: 'discount-enhanced',
        name: 'Discount Calculator',
        description: 'Calculate discounts and savings',
        icon: 'percent',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'DiscountApp',
    },
    {
        id: 'text-reverser',
        name: 'Text Reverser',
        description: 'Reverse any text string',
        icon: 'rotate-ccw',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TextReverserApp',
    },
    {
        id: 'url-encoder',
        name: 'URL Encoder',
        description: 'Encode and decode URLs',
        icon: 'link',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'URLEncoderApp',
    },
    {
        id: 'html-entity',
        name: 'HTML Entity',
        description: 'Encode and decode HTML entities',
        icon: 'code',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'HTMLEntityApp',
    },
    {
        id: 'alarm',
        name: 'Alarm Clock',
        description: 'Set multiple alarms',
        icon: 'alarm-clock',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'AlarmApp',
    },
    {
        id: 'credit-card',
        name: 'Credit Card Validator',
        description: 'Validate credit card numbers (Luhn algorithm)',
        icon: 'credit-card',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'CreditCardApp',
    },
    {
        id: 'text-diff',
        name: 'Text Similarity',
        description: 'Compare text similarity percentage',
        icon: 'diff',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TextDiffApp',
    },
    {
        id: 'barcode',
        name: 'Barcode Visualizer',
        description: 'Generate simple barcode visualization',
        icon: 'barcode',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'BarcodeApp',
    },
    {
        id: 'iban-validator',
        name: 'IBAN Validator',
        description: 'Validate international bank account numbers',
        icon: 'building-2',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'IBANValidatorApp',
    },
    {
        id: 'random-name',
        name: 'Random Name',
        description: 'Generate random names for testing',
        icon: 'user',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'RandomNameApp',
    },
    {
        id: 'ip-calculator',
        name: 'IP Subnet Calculator',
        description: 'Calculate subnet masks and network info',
        icon: 'network',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'IPCalculatorApp',
    },
    {
        id: 'weather',
        name: 'Weather',
        description: 'Real-time weather forecast with 7-day predictions',
        icon: 'cloud-sun',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'productivity',
        badge: { type: 'popular', text: 'Popular' },
        component: 'WeatherApp',
    },
    {
        id: 'calculator',
        name: 'Calculator',
        description: 'Scientific calculator with history',
        icon: 'calculator',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'productivity',
        component: 'CalculatorApp',
    },
    {
        id: 'notes',
        name: 'Quick Notes',
        description: 'Take notes with local storage backup',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'productivity',
        component: 'NotesApp',
    },
    {
        id: 'timer',
        name: 'Timer',
        description: 'Stopwatch and countdown timer',
        icon: 'timer',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'TimerApp',
    },
    {
        id: 'pomodoro',
        name: 'Pomodoro',
        description: 'Focus timer with work/break cycles',
        icon: 'clock',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'productivity',
        badge: { type: 'hot', text: 'Hot' },
        component: 'PomodoroApp',
    },
    {
        id: 'unitconverter',
        name: 'Unit Converter',
        description: 'Convert length, weight, temperature & more',
        icon: 'ruler',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'UnitConverterApp',
    },
    {
        id: 'crypto',
        name: 'Crypto Tracker',
        description: 'Top 20 cryptocurrencies with live prices',
        icon: 'trending-up',
        gradient: 'linear-gradient(135deg, #f7931a, #f59e0b)',
        category: 'finance',
        badge: { type: 'popular', text: 'Popular' },
        component: 'CryptoApp',
    },
    {
        id: 'currency',
        name: 'Currency Exchange',
        description: 'Live exchange rates for 150+ currencies',
        icon: 'banknote',
        gradient: 'linear-gradient(135deg, #22c55e, #10b981)',
        category: 'finance',
        component: 'CurrencyApp',
    },
    {
        id: 'quotes',
        name: 'Daily Quotes',
        description: 'Inspirational quotes with save feature',
        icon: 'quote',
        gradient: 'linear-gradient(135deg, #a855f7, #6366f1)',
        category: 'info',
        component: 'QuotesApp',
    },
    {
        id: 'countries',
        name: 'World Atlas',
        description: 'Explore 250+ countries with detailed info',
        icon: 'globe',
        gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)',
        category: 'info',
        component: 'CountriesApp',
    },
    {
        id: 'dictionary',
        name: 'Dictionary',
        description: 'Look up words with definitions & audio',
        icon: 'book-open',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        category: 'info',
        component: 'DictionaryApp',
    },
    {
        id: 'github',
        name: 'GitHub Finder',
        description: 'Search GitHub users and profiles',
        icon: 'github',
        gradient: 'linear-gradient(135deg, #374151, #1f2937)',
        category: 'productivity',
        component: 'GitHubApp',
    },
    {
        id: 'jokes',
        name: 'Random Jokes',
        description: 'Programming & general jokes',
        icon: 'smile',
        gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
        category: 'fun',
        component: 'JokesApp',
    },
    {
        id: 'trivia',
        name: 'Trivia Quiz',
        description: 'Test your knowledge with random trivia',
        icon: 'brain',
        gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
        category: 'fun',
        badge: { type: 'popular', text: 'Popular' },
        component: 'TriviaApp',
    },
    {
        id: 'pokemon',
        name: 'Pokédex',
        description: 'Explore 1000+ Pokémon with stats',
        icon: 'zap',
        gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
        category: 'entertainment',
        component: 'PokemonApp',
    },
    {
        id: 'catfacts',
        name: 'Cat Facts',
        description: 'Random fun facts about cats',
        icon: 'cat',
        gradient: 'linear-gradient(135deg, #f472b6, #ec4899)',
        category: 'fun',
        component: 'CatFactsApp',
    },
    {
        id: 'dogimages',
        name: 'Dog Gallery',
        description: 'Random adorable dog pictures',
        icon: 'dog',
        gradient: 'linear-gradient(135deg, #a78bfa, #8b5cf6)',
        category: 'fun',
        component: 'DogGalleryApp',
    },
    {
        id: 'advice',
        name: 'Life Advice',
        description: 'Get random life advice',
        icon: 'lightbulb',
        gradient: 'linear-gradient(135deg, #6366f1, #4f46e5)',
        category: 'info',
        component: 'AdviceApp',
    },
    {
        id: 'bored',
        name: 'Activity Finder',
        description: 'Find activities when you are bored',
        icon: 'sparkles',
        gradient: 'linear-gradient(135deg, #f472b6, #ec4899)',
        category: 'fun',
        component: 'BoredApp',
    },
    {
        id: 'qrcode',
        name: 'QR Generator',
        description: 'Generate QR codes for any text or URL',
        icon: 'qr-code',
        gradient: 'linear-gradient(135deg, #1f2937, #374151)',
        category: 'utility',
        component: 'QRCodeApp',
    },
    {
        id: 'colors',
        name: 'Color Palette',
        description: 'Generate beautiful color palettes',
        icon: 'palette',
        gradient: 'linear-gradient(135deg, #f472b6, #f59e0b)',
        category: 'utility',
        component: 'ColorsApp',
    },
    {
        id: 'ipinfo',
        name: 'IP Info',
        description: 'Get your IP address and location info',
        icon: 'wifi',
        gradient: 'linear-gradient(135deg, #3b82f6, #06b6d4)',
        category: 'utility',
        component: 'IPInfoApp',
    },
    {
        id: 'hashgenerator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA-1, SHA-256, SHA-512 & Base64',
        icon: 'hash',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'HashGeneratorApp',
    },
    {
        id: 'texttools',
        name: 'Text Tools',
        description: 'Transform, analyze & manipulate text',
        icon: 'type',
        gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TextToolsApp',
    },
    {
        id: 'passwordgen',
        name: 'Password Generator',
        description: 'Create strong, secure passwords',
        icon: 'key',
        gradient: 'linear-gradient(135deg, #6366f1, #06b6d4)',
        category: 'utility',
        badge: { type: 'hot', text: 'Hot' },
        component: 'PasswordGeneratorApp',
    },
    {
        id: 'datecalc',
        name: 'Date Calculator',
        description: 'Calculate date differences & add/subtract dates',
        icon: 'calendar',
        gradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
        category: 'productivity',
        component: 'DateCalculatorApp',
    },
    {
        id: 'jsonformatter',
        name: 'JSON Formatter',
        description: 'Format & minify JSON with validation',
        icon: 'file-json',
        gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)',
        category: 'utility',
        component: 'JsonFormatterApp',
    },
    {
        id: 'base64',
        name: 'Base64 Encoder',
        description: 'Encode & decode Base64 strings',
        icon: 'binary',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'utility',
        component: 'Base64App',
    },
    {
        id: 'loremipsum',
        name: 'Lorem Ipsum',
        description: 'Generate placeholder text for designs',
        icon: 'text',
        gradient: 'linear-gradient(135deg, #8b5cf6, #d946ef)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'LoremIpsumApp',
    },
    {
        id: 'regextester',
        name: 'Regex Tester',
        description: 'Test and debug regular expressions',
        icon: 'code',
        gradient: 'linear-gradient(135deg, #14b8a6, #22c55e)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'RegexTesterApp',
    },
    {
        id: 'emojipicker',
        name: 'Emoji Picker',
        description: 'Search and copy emojis easily',
        icon: 'smile',
        gradient: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'EmojiPickerApp',
    },
    {
        id: 'markdown',
        name: 'Markdown Preview',
        description: 'Write and preview markdown in real-time',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'productivity',
        badge: { type: 'hot', text: 'Hot' },
        component: 'MarkdownPreviewApp',
    },
    {
        id: 'uuid',
        name: 'UUID Generator',
        description: 'Generate unique identifiers (UUID v4)',
        icon: 'fingerprint',
        gradient: 'linear-gradient(135deg, #8b5cf6, #06b6d4)',
        category: 'utility',
        component: 'UUIDGeneratorApp',
    },
    {
        id: 'gradient',
        name: 'Gradient Generator',
        description: 'Create beautiful CSS gradients',
        icon: 'paintbrush',
        gradient: 'linear-gradient(135deg, #ec4899, #f59e0b)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'GradientGeneratorApp',
    },
    {
        id: 'countdown',
        name: 'Countdown Timer',
        description: 'Count down to important events',
        icon: 'calendar-clock',
        gradient: 'linear-gradient(135deg, #ef4444, #ec4899)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'CountdownApp',
    },
    {
        id: 'randomnumber',
        name: 'Random Number',
        description: 'Generate random numbers with range',
        icon: 'dices',
        gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'RandomNumberApp',
    },
    {
        id: 'percentage',
        name: 'Percentage Calculator',
        description: 'Calculate percentages easily',
        icon: 'percent',
        gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)',
        category: 'utility',
        component: 'PercentageApp',
    },
    {
        id: 'worldclock',
        name: 'World Clock',
        description: 'View time in different timezones',
        icon: 'globe-2',
        gradient: 'linear-gradient(135deg, #3b82f6, #06b6d4)',
        category: 'productivity',
        badge: { type: 'hot', text: 'Hot' },
        component: 'WorldClockApp',
    },
    {
        id: 'aspectratio',
        name: 'Aspect Ratio',
        description: 'Calculate aspect ratios for design',
        icon: 'ratio',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'utility',
        component: 'AspectRatioApp',
    },
    {
        id: 'numberbase',
        name: 'Number Base',
        description: 'Convert between decimal, binary, hex, octal',
        icon: 'binary',
        gradient: 'linear-gradient(135deg, #14b8a6, #3b82f6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'NumberBaseApp',
    },
    {
        id: 'translator',
        name: 'Translator',
        description: 'Translate text between 18+ languages',
        icon: 'languages',
        gradient: 'linear-gradient(135deg, #6366f1, #06b6d4)',
        category: 'productivity',
        badge: { type: 'hot', text: 'Hot' },
        component: 'TranslatorApp',
    },
    {
        id: 'wordcounter',
        name: 'Word Counter',
        description: 'Count words, characters, sentences & more',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
        category: 'productivity',
        component: 'WordCounterApp',
    },
    {
        id: 'agecalculator',
        name: 'Age Calculator',
        description: 'Calculate exact age with zodiac sign',
        icon: 'cake',
        gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'AgeCalculatorApp',
    },
    {
        id: 'bmi',
        name: 'BMI Calculator',
        description: 'Calculate Body Mass Index with health advice',
        icon: 'heart-pulse',
        gradient: 'linear-gradient(135deg, #22c55e, #10b981)',
        category: 'utility',
        component: 'BMICalculatorApp',
    },
    {
        id: 'urlshortener',
        name: 'URL Shortener',
        description: 'Shorten long URLs instantly',
        icon: 'link',
        gradient: 'linear-gradient(135deg, #f59e0b, #22c55e)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'UrlShortenerApp',
    },
    {
        id: 'imageconverter',
        name: 'Image Converter',
        description: 'Convert images between PNG, JPEG, WebP, BMP',
        icon: 'image',
        gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'ImageConverterApp',
    },
    {
        id: 'pdftools',
        name: 'PDF Tools',
        description: 'Merge, compress, and convert PDF files',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'utility',
        badge: { type: 'hot', text: 'Hot' },
        component: 'PDFToolsApp',
    },
    {
        id: 'documentconverter',
        name: 'Document Converter',
        description: 'Convert PDF, Word, Excel, and TXT files',
        icon: 'file-stack',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'DocumentConverterApp',
    },
    {
        id: 'audioconverter',
        name: 'Audio Converter',
        description: 'Convert audio files: MP3, WAV, OGG, AAC',
        icon: 'music',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'AudioConverterApp',
    },
    {
        id: 'videoconverter',
        name: 'Video Converter',
        description: 'Convert video files: MP4, WebM, AVI, MOV',
        icon: 'video',
        gradient: 'linear-gradient(135deg, #14b8a6, #22c55e)',
        category: 'utility',
        badge: { type: 'hot', text: 'Hot' },
        component: 'VideoConverterApp',
    },
    {
        id: 'texttospeech',
        name: 'Text to Speech',
        description: 'Convert text to speech with voice controls',
        icon: 'volume-2',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TextToSpeechApp',
    },
    {
        id: 'speechtotext',
        name: 'Speech to Text',
        description: 'Convert voice to text in real-time',
        icon: 'mic',
        gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'SpeechToTextApp',
    },
    {
        id: 'imageresizer',
        name: 'Image Resizer',
        description: 'Resize images with aspect ratio control',
        icon: 'maximize',
        gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'ImageResizerApp',
    },
    {
        id: 'imagecompressor',
        name: 'Image Compressor',
        description: 'Reduce image file size with quality control',
        icon: 'minimize',
        gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'ImageCompressorApp',
    },
    {
        id: 'loancalculator',
        name: 'Loan Calculator',
        description: 'Calculate loan payments and interest',
        icon: 'wallet',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'LoanCalculatorApp',
    },
    {
        id: 'discountcalculator',
        name: 'Discount Calculator',
        description: 'Calculate savings from discounts',
        icon: 'tag',
        gradient: 'linear-gradient(135deg, #ec4899, #f97316)',
        category: 'utility',
        badge: { type: 'hot', text: 'Hot' },
        component: 'DiscountCalculatorApp',
    },
    {
        id: 'tipcalculator',
        name: 'Tip Calculator',
        description: 'Calculate tips and split bills',
        icon: 'receipt',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'TipCalculatorApp',
    },
    {
        id: 'invoicegenerator',
        name: 'Invoice Generator',
        description: 'Create professional invoices with print support',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'InvoiceGeneratorApp',
    },
    {
        id: 'flashcard',
        name: 'Flashcards',
        description: 'Learn with spaced repetition flashcards',
        icon: 'book-open',
        gradient: 'linear-gradient(135deg, #10b981, #06b6d4)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'FlashcardApp',
    },
    {
        id: 'habittracker',
        name: 'Habit Tracker',
        description: 'Track daily habits and build streaks',
        icon: 'target',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'productivity',
        badge: { type: 'hot', text: 'Hot' },
        component: 'HabitTrackerApp',
    },
    {
        id: 'morsecode',
        name: 'Morse Code',
        description: 'Translate text to/from Morse code with audio',
        icon: 'radio',
        gradient: 'linear-gradient(135deg, #22c55e, #10b981)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'MorseCodeApp',
    },
    {
        id: 'colorblindness',
        name: 'Color Blindness Simulator',
        description: 'Test design accessibility for color blind users',
        icon: 'eye',
        gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'ColorBlindnessApp',
    },
    {
        id: 'nasaapod',
        name: 'NASA Explorer',
        description: 'Astronomy Picture of the Day & ISS Tracker',
        icon: 'telescope',
        gradient: 'linear-gradient(135deg, #1e3a5f, #4a90a4)',
        category: 'info',
        badge: { type: 'hot', text: 'Hot' },
        component: 'NasaApodApp',
    },
    {
        id: 'breathing',
        name: 'Breathing Exercise',
        description: 'Guided breathing for relaxation and focus',
        icon: 'wind',
        gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'BreathingApp',
    },
    {
        id: 'stopwatch',
        name: 'Stopwatch',
        description: 'Precision timing with lap tracking',
        icon: 'timer',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'StopwatchApp',
    },
    {
        id: 'coinflip',
        name: 'Coin Flip',
        description: 'Let fate decide with a coin toss',
        icon: 'coins',
        gradient: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'CoinFlipApp',
    },
    {
        id: 'decisionwheel',
        name: 'Decision Wheel',
        description: 'Spin the wheel to make decisions',
        icon: 'target',
        gradient: 'linear-gradient(135deg, #8b5cf6, #d946ef)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'DecisionWheelApp',
    },
    {
        id: 'rps',
        name: 'Rock Paper Scissors',
        description: 'Classic game against the computer',
        icon: 'swords',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'RockPaperScissorsApp',
    },
    {
        id: 'magic8ball',
        name: 'Magic 8 Ball',
        description: 'Ask questions, get mystical answers',
        icon: 'sparkles',
        gradient: 'linear-gradient(135deg, #1e1b4b, #4c1d95)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'Magic8BallApp',
    },
    {
        id: 'typingspeed',
        name: 'Typing Speed Test',
        description: 'Test your typing speed and accuracy',
        icon: 'keyboard',
        gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
        category: 'fun',
        badge: { type: 'hot', text: 'Hot' },
        component: 'TypingSpeedApp',
    },
    {
        id: 'caseconverter',
        name: 'Case Converter',
        description: 'Convert text between different cases',
        icon: 'type',
        gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'CaseConverterApp',
    },
    {
        id: 'tictactoe',
        name: 'Tic Tac Toe',
        description: 'Classic X vs O game against AI',
        icon: 'gamepad-2',
        gradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
        category: 'fun',
        badge: { type: 'new', text: 'New' },
        component: 'TicTacToeApp',
    },
];

export const CATEGORIES = [
    { id: 'all', label: 'All Apps', icon: 'layout-grid' },
    { id: 'favorites', label: 'Favorites', icon: 'heart' },
    { id: 'productivity', label: 'Productivity', icon: 'zap' },
    { id: 'finance', label: 'Finance', icon: 'wallet' },
    { id: 'entertainment', label: 'Entertainment', icon: 'tv' },
    { id: 'info', label: 'Information', icon: 'book-open' },
    { id: 'fun', label: 'Fun', icon: 'gamepad-2' },
    { id: 'utility', label: 'Utilities', icon: 'wrench' },
] as const;
