import { MiniApp } from '@/types';

export const MINI_APPS: MiniApp[] = [
    // Info & Content
    {
        id: 'news-headlines',
        name: 'News',
        description: 'Latest news headlines by category',
        icon: 'newspaper',
        gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
        category: 'info',
        badge: { type: 'popular', text: 'Popular' },
        component: 'NewsApp',
    },
    {
        id: 'movie-db',
        name: 'Movies',
        description: 'Search movies and TV shows',
        icon: 'film',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'entertainment',
        badge: { type: 'new', text: 'New' },
        component: 'MovieDatabaseApp',
    },
    {
        id: 'book-search',
        name: 'Books',
        description: 'Search books from Open Library',
        icon: 'book-open',
        gradient: 'linear-gradient(135deg, #f59e0b, #eab308)',
        category: 'info',
        badge: { type: 'new', text: 'New' },
        component: 'BookSearchApp',
    },
    {
        id: 'wikipedia',
        name: 'Wikipedia',
        description: 'Search Wikipedia articles',
        icon: 'globe',
        gradient: 'linear-gradient(135deg, #06b6d4, #0ea5e9)',
        category: 'info',
        badge: { type: 'new', text: 'New' },
        component: 'WikipediaApp',
    },
    {
        id: 'reddit',
        name: 'Reddit',
        description: 'Browse Reddit posts and subreddits',
        icon: 'message-circle',
        gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
        category: 'entertainment',
        badge: { type: 'new', text: 'New' },
        component: 'RedditBrowserApp',
    },
    {
        id: 'dictionary',
        name: 'Dictionary',
        description: 'Look up words with definitions & audio',
        icon: 'book-open',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        category: 'info',
        component: 'DictionaryApp',
    },
    {
        id: 'countries',
        name: 'World Atlas',
        description: 'Explore 250+ countries with detailed info',
        icon: 'globe',
        gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)',
        category: 'info',
        component: 'CountriesApp',
    },
    {
        id: 'quotes',
        name: 'Daily Quotes',
        description: 'Inspirational quotes with save feature',
        icon: 'quote',
        gradient: 'linear-gradient(135deg, #a855f7, #6366f1)',
        category: 'info',
        component: 'QuotesApp',
    },
    {
        id: 'product-search',
        name: 'Product Search',
        description: 'Search and browse products',
        icon: 'shopping-bag',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        category: 'info',
        badge: { type: 'new', text: 'New' },
        component: 'ProductSearchApp',
    },

    // Finance & Data
    {
        id: 'weather',
        name: 'Weather',
        description: 'Real-time weather forecast with 7-day predictions',
        icon: 'cloud-sun',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'productivity',
        badge: { type: 'popular', text: 'Popular' },
        component: 'WeatherApp',
    },
    {
        id: 'crypto',
        name: 'Crypto Tracker',
        description: 'Top 20 cryptocurrencies with live prices',
        icon: 'trending-up',
        gradient: 'linear-gradient(135deg, #f7931a, #f59e0b)',
        category: 'finance',
        badge: { type: 'popular', text: 'Popular' },
        component: 'CryptoApp',
    },
    {
        id: 'stock-market',
        name: 'Stock Market',
        description: 'Live stock prices and market data',
        icon: 'trending-up',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'finance',
        badge: { type: 'hot', text: 'Hot' },
        component: 'StockMarketApp',
    },
    {
        id: 'currency',
        name: 'Currency Exchange',
        description: 'Live exchange rates for 150+ currencies',
        icon: 'banknote',
        gradient: 'linear-gradient(135deg, #22c55e, #10b981)',
        category: 'finance',
        component: 'CurrencyApp',
    },
    {
        id: 'npm-search',
        name: 'NPM Search',
        description: 'Search NPM packages',
        icon: 'package',
        gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'NPMSearchApp',
    },

    // Developer Tools
    {
        id: 'api-tester',
        name: 'API Tester',
        description: 'Test REST APIs with custom headers',
        icon: 'code',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'APITesterApp',
    },
    {
        id: 'github',
        name: 'GitHub Finder',
        description: 'Search GitHub users and profiles',
        icon: 'github',
        gradient: 'linear-gradient(135deg, #374151, #1f2937)',
        category: 'productivity',
        component: 'GitHubApp',
    },
    {
        id: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode & validate JWT tokens',
        icon: 'key',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'JWTDecoderApp',
    },
    {
        id: 'timestamp',
        name: 'Timestamp',
        description: 'Convert Unix timestamp to human time',
        icon: 'clock',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'utility',
        badge: { type: 'new', text: 'New' },
        component: 'TimestampConverterApp',
    },
    {
        id: 'base64',
        name: 'Base64 Encoder',
        description: 'Encode & decode Base64 strings',
        icon: 'binary',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        category: 'utility',
        component: 'Base64App',
    },
    {
        id: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Format and validate JSON data',
        icon: 'braces',
        gradient: 'linear-gradient(135deg, #06b6d4, #0ea5e9)',
        category: 'utility',
        component: 'JSONFormatterApp',
    },
    {
        id: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA1, SHA256 hashes',
        icon: 'hash',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        category: 'utility',
        component: 'HashGeneratorApp',
    },
    {
        id: 'uuid',
        name: 'UUID Generator',
        description: 'Generate unique identifiers (UUID v4)',
        icon: 'fingerprint',
        gradient: 'linear-gradient(135deg, #8b5cf6, #06b6d4)',
        category: 'utility',
        component: 'UUIDGeneratorApp',
    },

    // File Converters
    {
        id: 'image-converter',
        name: 'Image Converter',
        description: 'Convert images between formats',
        icon: 'image',
        gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
        category: 'utility',
        component: 'ImageConverterApp',
    },
    {
        id: 'audio-converter',
        name: 'Audio Converter',
        description: 'Convert audio files',
        icon: 'music',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'utility',
        component: 'AudioConverterApp',
    },
    {
        id: 'video-converter',
        name: 'Video Converter',
        description: 'Convert video files',
        icon: 'video',
        gradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
        category: 'utility',
        component: 'VideoConverterApp',
    },
    {
        id: 'document-converter',
        name: 'Document Converter',
        description: 'Convert document formats',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'utility',
        component: 'DocumentConverterApp',
    },
    {
        id: 'pdf-tools',
        name: 'PDF Tools',
        description: 'Merge, split & compress PDFs',
        icon: 'file',
        gradient: 'linear-gradient(135deg, #ef4444, #f43f5e)',
        category: 'utility',
        component: 'PDFToolsApp',
    },

    // Productivity
    {
        id: 'todo-list',
        name: 'Todo List',
        description: 'Organize tasks with categories, priorities, and due dates',
        icon: 'list-checks',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        category: 'productivity',
        badge: { type: 'new', text: 'New' },
        component: 'TodoListApp',
    },
    {
        id: 'expense-tracker',
        name: 'Expense Tracker',
        description: 'Track income and expenses with visual breakdown',
        icon: 'wallet',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        category: 'finance',
        badge: { type: 'new', text: 'New' },
        component: 'ExpenseTrackerApp',
    },
    {
        id: 'notes',
        name: 'Quick Notes',
        description: 'Take notes with local storage backup',
        icon: 'file-text',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'productivity',
        component: 'NotesApp',
    },

    // Fun & Entertainment
    {
        id: 'jokes',
        name: 'Random Jokes',
        description: 'Programming & general jokes',
        icon: 'smile',
        gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
        category: 'fun',
        component: 'JokesApp',
    },
    {
        id: 'cat-facts',
        name: 'Cat Facts',
        description: 'Random cat facts from API',
        icon: 'cat',
        gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
        category: 'fun',
        component: 'CatFactsApp',
    },
    {
        id: 'dog-gallery',
        name: 'Dog Gallery',
        description: 'Random dog images from API',
        icon: 'dog',
        gradient: 'linear-gradient(135deg, #eab308, #facc15)',
        category: 'fun',
        component: 'DogGalleryApp',
    },
    {
        id: 'trivia',
        name: 'Trivia Quiz',
        description: 'Test your knowledge with random trivia',
        icon: 'brain',
        gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
        category: 'fun',
        badge: { type: 'popular', text: 'Popular' },
        component: 'TriviaApp',
    },
    {
        id: 'pokemon',
        name: 'Pokédex',
        description: 'Explore 1000+ Pokémon with stats',
        icon: 'zap',
        gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
        category: 'entertainment',
        component: 'PokemonApp',
    },

    // Utilities
    {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Generate secure random passwords',
        icon: 'lock',
        gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
        category: 'utility',
        component: 'PasswordGeneratorApp',
    },
    {
        id: 'qr-code',
        name: 'QR Code Generator',
        description: 'Generate QR codes from text',
        icon: 'qr-code',
        gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
        category: 'utility',
        component: 'QRCodeApp',
    },
    {
        id: 'ip-info',
        name: 'IP Lookup',
        description: 'Get IP address information',
        icon: 'globe',
        gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)',
        category: 'utility',
        component: 'IPInfoApp',
    },
    {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test regular expressions',
        icon: 'code',
        gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
        category: 'utility',
        component: 'RegexTesterApp',
    },
];

export const CATEGORIES = [
    { id: 'all', name: 'All Apps', icon: 'grid' },
    { id: 'productivity', name: 'Productivity', icon: 'briefcase' },
    { id: 'finance', name: 'Finance', icon: 'dollar-sign' },
    { id: 'entertainment', name: 'Entertainment', icon: 'tv' },
    { id: 'info', name: 'Information', icon: 'info' },
    { id: 'fun', name: 'Fun', icon: 'smile' },
    { id: 'utility', name: 'Utilities', icon: 'tool' },
] as const;
